### ISSUE TITLE
lost & found form

### ISSUE THREAD

**Issue by DerGernTod** [DerGernTod/streunerkatzen#29]
create a lost & found form based on http://katzensuche.streunerkatzen.org/index.php?option=com_sobi2&sobi2Task=addNew&Itemid=54
- [x] ~show example images when it comes to coloring (requires some kind of hint popup)~ see #34 
- [x] ~special form elements that support hints~ see #34 
- [x] create cat entry "draft" upon form submission, email to admin, requires activation
- [x] ~captcha~ see #35
- [x] link entry to user
- [x] ~remind users of their unresolved entries after x weeks (admin config)~ see #36 
- [x] ~add timeframe (when was it lost?)~ see #32

**Comment by DerGernTod** [comment]
a few more issues:
* renamed the form fields internally, so it'll still work even if form labels are changed. this requires more changes though
* fixed a bug with the catform setting

todo:
- [x] update createCat function to work with renamed form fields (and takes names instead of titles (labels)
- [x] fix dropdowns: store dropdown data in `Cat.php` just as string, use `CatField_...` options for dropdown in `getCmsFields`
- [x] db cleanup (remove existing cats and form submissions)
